version: "3.7"
services:
  papyrus_app:
    image: papyrus
    container_name: pps_app
    ports:
      - 9090:9090
    depends_on:
      papyrus_db:
        condition: service_healthy

  papyrus_db:
    image: postgres:15
    container_name: pps_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
        # 
        # networks:
        #   papyrus-net:
        #     driver: bridge
        #     ipam:
        #       driver: default
