version: "3.7"
services:
  papyrus_app:
    image: papyrus
    container_name: pps_app
    ports:
      - 9090:9090
    depends_on:
      papyrus_db:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json

  papyrus_db:
    image: postgres:15
    container_name: pps_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=papyrus
      - POSTGRES_USER=mastersoft
      - POSTGRES_PASSWORD=mastersoft
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  papyrus-net:
    driver: bridge
    ipam:
      driver: default
