version: "3.7"
services:
  postgresql:
    image: postgres:15
    container_name: papyrus_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=papyrus
      - POSTGRES_USER=mastersoft
      - POSTGRES_PASSWORD=mastersoft
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
